name: econ
ckpt_dir: "./data/ckpt/"
normal_path: "./data/ckpt/normal/last.ckpt"
ifnet_path: "./data/ckpt/IF-Geo/last-256.ckpt"
results_path: "./results"

net:
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))

test_mode: True
batch_size: 1

# user defined
vol_res: 256      # IF-Net volume resolution
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: True  # if True, will remove floating pieces
cloth_overlap_thres: 0.50
body_overlap_thres: 0.93

# use_smpl: ["hand", "face"]
use_smpl: []
always_ifnet: True
