name: normal
ckpt_dir: "./data/ckpt/"
resume_path: "./data/ckpt/normal/last.ckpt"
results_path: "./results"

dataset:
  root: "./data/"
  rotation_num: 12
  train_bsize: 1.0
  val_bsize: 1.0
  test_bsize: 1.0
  # types: ["thuman2"]
  # scales: [100.0]
  types: ["3dpeople","axyz","renderpeople","renderpeople_p27","humanalloy","thuman2"]
  scales: [1.0, 100.0, 1.0, 1.0, 2.54000508001016, 100.0]

net:
  use_gan: True
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))

lr_Gen: 1e-4
lr_Dis: 1e-4
weight_decay: 0.0 
momentum: 0.0

batch_size: 3
num_threads: 3
devices: 6

fast_dev: 0
resume: False
test_mode: False
num_sanity_val_steps: 1

momentum: 0.0 
optim: Adam

overfit: False
num_epoch: 20
freq_show_train: 0.1
freq_show_val: 0.01
freq_plot: 0.01
freq_eval: 0.1
schedule: [18]
